<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="BowtieWrapper.fs" />
        <Compile Include="HGVS.fs" />
        <Compile Include="Sequence.fs" />
        <Compile Include="SequenceRepository.fs" />
        <Compile Include="SpacerFinder.fs" />
    </ItemGroup>

    <ItemGroup>
      <None Include="LibraryTesting.fsx" />
    </ItemGroup>

</Project>
