<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <PropertyGroup>
        <RazorCompileOnBuild>true</RazorCompileOnBuild>
        <RazorCompileOnPublish>true</RazorCompileOnPublish>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\gRNA\gRNA.fsproj" />
    </ItemGroup>


    <ItemGroup>
      <None Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </None>
    </ItemGroup>

    
    

</Project>
